// BlockNameMapper - 方块名称映射
// 用于粒子材质名称转换
// 注意：资源包中的纹理和粒子定义使用 Java 版名称，所以大多数情况下不需要映射

const JAVA_TO_BEDROCK_BLOCK_MAP = {
    'smooth_quartz': 'quartz_block_bottom',
    'quartz_block': 'quartz_block_side',
    'chiseled_quartz_block': 'chiseled_quartz_block',
    'quartz_pillar': 'quartz_pillar',
    'quartz_bricks': 'quartz_bricks',
    'spawner': 'spawner',
    'moving_piston': 'piston_arm_collision',
    'piston_head': 'piston_arm_collision',
    'grass_path': 'dirt_path_top',
    'grass_block': 'grass_block_top',
    'stone_bricks': 'stone_bricks',
    'mossy_stone_bricks': 'mossy_stone_bricks',
    'cracked_stone_bricks': 'cracked_stone_bricks',
    'chiseled_stone_bricks': 'chiseled_stone_bricks',
    'end_stone_bricks': 'end_stone_bricks',
    'red_nether_bricks': 'red_nether_bricks',
    'nether_bricks': 'nether_bricks',
    'cracked_nether_bricks': 'cracked_nether_bricks',
    'chiseled_nether_bricks': 'chiseled_nether_bricks',
    'polished_blackstone_bricks': 'polished_blackstone_bricks',
    'cracked_polished_blackstone_bricks': 'cracked_polished_blackstone_bricks',
    'chiseled_polished_blackstone': 'chiseled_polished_blackstone',
    'deepslate_bricks': 'deepslate_bricks',
    'cracked_deepslate_bricks': 'cracked_deepslate_bricks',
    'deepslate_tiles': 'deepslate_tiles',
    'cracked_deepslate_tiles': 'cracked_deepslate_tiles',
    'chiseled_deepslate': 'chiseled_deepslate',
    'cobbled_deepslate': 'cobbled_deepslate',
    'polished_deepslate': 'polished_deepslate',
    'tuff_bricks': 'tuff_bricks',
    'polished_tuff': 'polished_tuff',
    'mud_bricks': 'mud_bricks',
    'packed_mud': 'packed_mud',
    'moss_block': 'moss_block',
    'moss_carpet': 'moss_carpet',
    'mycelium': 'mycelium_top',
    'podzol': 'podzol_top',
    'coarse_dirt': 'coarse_dirt',
    'rooted_dirt': 'rooted_dirt',
    'farmland': 'farmland',
    'farmland_moist': 'farmland_moist',
    'dirt_path': 'dirt_path_top',
    'stone': 'stone',
    'cobblestone': 'cobblestone',
    'mossy_cobblestone': 'mossy_cobblestone',
    'diorite': 'diorite',
    'andesite': 'andesite',
    'granite': 'granite',
    'polished_diorite': 'polished_diorite',
    'polished_andesite': 'polished_andesite',
    'polished_granite': 'polished_granite',
    'calcite': 'calcite',
    'tuff': 'tuff',
    'dripstone_block': 'dripstone_block',
    'amethyst_block': 'amethyst_block',
    'budding_amethyst': 'budding_amethyst',
    'copper_block': 'copper_block',
    'exposed_copper': 'exposed_copper',
    'weathered_copper': 'weathered_copper',
    'oxidized_copper': 'oxidized_copper',
    'cut_copper': 'cut_copper',
    'exposed_cut_copper': 'exposed_cut_copper',
    'weathered_cut_copper': 'weathered_cut_copper',
    'oxidized_cut_copper': 'oxidized_cut_copper',
    'raw_copper_block': 'raw_copper_block',
    'raw_gold_block': 'raw_gold_block',
    'raw_iron_block': 'raw_iron_block',
    'netherite_block': 'netherite_block',
    'ancient_debris': 'ancient_debris_top',
    'lodestone': 'lodestone_top',
    'respawn_anchor': 'respawn_anchor_top',
    'crying_obsidian': 'crying_obsidian',
    'blackstone': 'blackstone_top',
    'polished_blackstone': 'polished_blackstone',
    'basalt': 'basalt_top',
    'polished_basalt': 'polished_basalt_top',
    'smooth_basalt': 'smooth_basalt',
    'gilded_blackstone': 'gilded_blackstone',
    'crying_obsidian': 'crying_obsidian',
    'lightning_rod': 'lightning_rod',
    'target': 'target_top',
    'honeycomb_block': 'honeycomb_block',
    'honey_block': 'honey_block_top',
    'bee_nest': 'bee_nest_front',
    'beehive': 'beehive_front',
    'conduit': 'conduit',
    'sea_lantern': 'sea_lantern',
    'prismarine': 'prismarine',
    'dark_prismarine': 'dark_prismarine',
    'prismarine_bricks': 'prismarine_bricks',
    'sea_pickle': 'sea_pickle',
    'brain_coral': 'brain_coral',
    'bubble_coral': 'bubble_coral',
    'fire_coral': 'fire_coral',
    'horn_coral': 'horn_coral',
    'tube_coral': 'tube_coral',
    'brain_coral_block': 'brain_coral_block',
    'bubble_coral_block': 'bubble_coral_block',
    'fire_coral_block': 'fire_coral_block',
    'horn_coral_block': 'horn_coral_block',
    'tube_coral_block': 'tube_coral_block',
    'kelp': 'kelp',
    'kelp_plant': 'kelp_plant',
    'seagrass': 'seagrass',
    'tall_seagrass': 'tall_seagrass',
    'cave_vines': 'cave_vines',
    'cave_vines_plant': 'cave_vines_plant',
    'glow_lichen': 'glow_lichen',
    'sculk': 'sculk',
    'sculk_catalyst': 'sculk_catalyst_top',
    'sculk_sensor': 'sculk_sensor_top',
    'sculk_shrieker': 'sculk_shrieker_top',
    'shroomlight': 'shroomlight',
    'crimson_nylium': 'crimson_nylium',
    'warped_nylium': 'warped_nylium',
    'crimson_stem': 'crimson_stem',
    'warped_stem': 'warped_stem',
    'stripped_crimson_stem': 'stripped_crimson_stem',
    'stripped_warped_stem': 'stripped_warped_stem',
    'crimson_planks': 'crimson_planks',
    'warped_planks': 'warped_planks',
    'crimson_fungus': 'crimson_fungus',
    'warped_fungus': 'warped_fungus',
    'crimson_roots': 'crimson_roots',
    'warped_roots': 'warped_roots',
    'nether_sprouts': 'nether_sprouts',
    'weeping_vines': 'weeping_vines',
    'twisting_vines': 'twisting_vines',
    'soul_soil': 'soul_soil',
    'soul_sand': 'soul_sand',
    'basalt': 'basalt_top',
    'soul_fire': 'soul_fire_0',
    'soul_torch': 'soul_torch',
    'soul_lantern': 'soul_lantern',
    'soul_campfire': 'soul_campfire_fire',
    'campfire': 'campfire_fire',
    'lantern': 'lantern',
    'bell': 'bell_top',
    'loom': 'loom_top',
    'barrel': 'barrel_top',
    'smoker': 'smoker_top',
    'blast_furnace': 'blast_furnace_top',
    'furnace': 'furnace_front',
    'cartography_table': 'cartography_table_top',
    'fletching_table': 'fletching_table_top',
    'smithing_table': 'smithing_table_top',
    'grindstone': 'grindstone_round',
    'stonecutter': 'stonecutter_top',
    'composter': 'composter_top',
    'lectern': 'lectern_top',
    'note_block': 'note_block',
    'jukebox': 'jukebox_top',
    'crafting_table': 'crafting_table_top',
    'enchanting_table': 'enchanting_table_top',
    'brewing_stand': 'brewing_stand',
    'cauldron': 'cauldron_top',
    'anvil': 'anvil_top',
    'chipped_anvil': 'chipped_anvil_top',
    'damaged_anvil': 'damaged_anvil_top',
    'beacon': 'beacon',
    'conduit': 'conduit',
    'end_rod': 'end_rod',
    'end_portal_frame': 'end_portal_frame_top',
    'dragon_egg': 'dragon_egg',
    'shulker_box': 'shulker_box',
    'bed': 'red_bed',
    'banner': 'white_banner',
    'skull': 'skeleton_skull',
    'structure_block': 'structure_block',
    'jigsaw': 'jigsaw_top',
    'observer': 'observer_front',
    'dispenser': 'dispenser_front',
    'dropper': 'dropper_front',
    'hopper': 'hopper_top',
    'daylight_detector': 'daylight_detector_top',
    'redstone_lamp': 'redstone_lamp',
    'redstone_torch': 'redstone_torch',
    'lever': 'lever',
    'tripwire_hook': 'tripwire_hook',
    'tripwire': 'tripwire',
    'lightning_rod': 'lightning_rod',
    'pointed_dripstone': 'pointed_dripstone',
    'small_dripleaf': 'small_dripleaf',
    'big_dripleaf': 'big_dripleaf_top',
    'azalea': 'azalea_top',
    'flowering_azalea': 'flowering_azalea_top',
    'azalea_leaves': 'azalea_leaves',
    'flowering_azalea_leaves': 'flowering_azalea_leaves',
    'hanging_roots': 'hanging_roots',
    'spore_blossom': 'spore_blossom',
    'glow_lichen': 'glow_lichen',
    'tinted_glass': 'tinted_glass',
    'powder_snow': 'powder_snow',
    'sculk_sensor': 'sculk_sensor_top',
    'calibrated_sculk_sensor': 'calibrated_sculk_sensor_top',
    'sculk_catalyst': 'sculk_catalyst_top',
    'sculk_shrieker': 'sculk_shrieker_top',
    'frogspawn': 'frogspawn',
    'mangrove_roots': 'mangrove_roots_top',
    'muddy_mangrove_roots': 'muddy_mangrove_roots_top',
    'mangrove_propagule': 'mangrove_propagule',
    'ochre_froglight': 'ochre_froglight_top',
    'verdant_froglight': 'verdant_froglight_top',
    'pearlescent_froglight': 'pearlescent_froglight_top',
    'reinforced_deepslate': 'reinforced_deepslate',
    'cherry_leaves': 'cherry_leaves',
    'cherry_sapling': 'cherry_sapling',
    'cherry_log': 'cherry_log',
    'cherry_planks': 'cherry_planks',
    'cherry_door': 'cherry_door_bottom',
    'cherry_trapdoor': 'cherry_trapdoor',
    'cherry_fence': 'cherry_fence',
    'cherry_fence_gate': 'cherry_fence_gate',
    'cherry_button': 'cherry_button',
    'cherry_pressure_plate': 'cherry_pressure_plate',
    'cherry_sign': 'cherry_sign',
    'bamboo_block': 'bamboo_block',
    'bamboo_mosaic': 'bamboo_mosaic',
    'bamboo_planks': 'bamboo_planks',
    'bamboo_door': 'bamboo_door_bottom',
    'bamboo_trapdoor': 'bamboo_trapdoor',
    'bamboo_fence': 'bamboo_fence',
    'bamboo_fence_gate': 'bamboo_fence_gate',
    'bamboo_button': 'bamboo_button',
    'bamboo_pressure_plate': 'bamboo_pressure_plate',
    'bamboo_sign': 'bamboo_sign',
    'suspicious_sand': 'suspicious_sand',
    'suspicious_gravel': 'suspicious_gravel',
    'sniffer_egg': 'sniffer_egg',
    'pitcher_crop': 'pitcher_crop_top',
    'torchflower': 'torchflower',
    'pink_petals': 'pink_petals',
    'pitcher_plant': 'pitcher_plant',
    'calibrated_sculk_sensor': 'calibrated_sculk_sensor_top',
    'chiseled_bookshelf': 'chiseled_bookshelf_top',
    'decorated_pot': 'decorated_pot',
    'crafter': 'crafter_top',
    'copper_grate': 'copper_grate',
    'exposed_copper_grate': 'exposed_copper_grate',
    'weathered_copper_grate': 'weathered_copper_grate',
    'oxidized_copper_grate': 'oxidized_copper_grate',
    'waxed_copper_grate': 'waxed_copper_grate',
    'waxed_exposed_copper_grate': 'waxed_exposed_copper_grate',
    'waxed_weathered_copper_grate': 'waxed_weathered_copper_grate',
    'waxed_oxidized_copper_grate': 'waxed_oxidized_copper_grate',
    'copper_bulb': 'copper_bulb',
    'exposed_copper_bulb': 'exposed_copper_bulb',
    'weathered_copper_bulb': 'weathered_copper_bulb',
    'oxidized_copper_bulb': 'oxidized_copper_bulb',
    'waxed_copper_bulb': 'waxed_copper_bulb',
    'waxed_exposed_copper_bulb': 'waxed_exposed_copper_bulb',
    'waxed_weathered_copper_bulb': 'waxed_weathered_copper_bulb',
    'waxed_oxidized_copper_bulb': 'waxed_oxidized_copper_bulb',
    'copper_door': 'copper_door_bottom',
    'exposed_copper_door': 'exposed_copper_door_bottom',
    'weathered_copper_door': 'weathered_copper_door_bottom',
    'oxidized_copper_door': 'oxidized_copper_door_bottom',
    'waxed_copper_door': 'waxed_copper_door_bottom',
    'waxed_exposed_copper_door': 'waxed_exposed_copper_door_bottom',
    'waxed_weathered_copper_door': 'waxed_weathered_copper_door_bottom',
    'waxed_oxidized_copper_door': 'waxed_oxidized_copper_door_bottom',
    'copper_trapdoor': 'copper_trapdoor',
    'exposed_copper_trapdoor': 'exposed_copper_trapdoor',
    'weathered_copper_trapdoor': 'weathered_copper_trapdoor',
    'oxidized_copper_trapdoor': 'oxidized_copper_trapdoor',
    'waxed_copper_trapdoor': 'waxed_copper_trapdoor',
    'waxed_exposed_copper_trapdoor': 'waxed_exposed_copper_trapdoor',
    'waxed_weathered_copper_trapdoor': 'waxed_weathered_copper_trapdoor',
    'waxed_oxidized_copper_trapdoor': 'waxed_oxidized_copper_trapdoor',
    'chiseled_copper': 'chiseled_copper',
    'exposed_chiseled_copper': 'exposed_chiseled_copper',
    'weathered_chiseled_copper': 'weathered_chiseled_copper',
    'oxidized_chiseled_copper': 'oxidized_chiseled_copper',
    'waxed_chiseled_copper': 'waxed_chiseled_copper',
    'waxed_exposed_chiseled_copper': 'waxed_exposed_chiseled_copper',
    'waxed_weathered_chiseled_copper': 'waxed_weathered_chiseled_copper',
    'waxed_oxidized_chiseled_copper': 'waxed_oxidized_chiseled_copper',
    'copper_chest': 'copper_chest',
    'exposed_copper_chest': 'exposed_copper_chest',
    'weathered_copper_chest': 'weathered_copper_chest',
    'oxidized_copper_chest': 'oxidized_copper_chest',
    'waxed_copper_chest': 'waxed_copper_chest',
    'waxed_exposed_copper_chest': 'waxed_exposed_copper_chest',
    'waxed_weathered_copper_chest': 'waxed_weathered_copper_chest',
    'waxed_oxidized_copper_chest': 'waxed_oxidized_copper_chest',
    'trial_spawner': 'trial_spawner_top_inactive',
    'vault': 'vault_top',
    'heavy_core': 'heavy_core',
    'breeze_rod': 'breeze_rod',
    'tropical_fish': 'tropical_fish',
    'pufferfish': 'pufferfish',
    'salmon': 'salmon',
    'cod': 'cod',
    'tropical_fish_bucket': 'tropical_fish_bucket',
    'pufferfish_bucket': 'pufferfish_bucket',
    'salmon_bucket': 'salmon_bucket',
    'cod_bucket': 'cod_bucket',
    'axolotl_bucket': 'axolotl_bucket',
    'tadpole_bucket': 'tadpole_bucket',
    'glow_ink_sac': 'glow_ink_sac',
    'glow_item_frame': 'glow_item_frame',
    'glow_squid_spawn_egg': 'glow_squid_spawn_egg',
    'glow_berries': 'glow_berries',
    'small_amethyst_bud': 'small_amethyst_bud',
    'medium_amethyst_bud': 'medium_amethyst_bud',
    'large_amethyst_bud': 'large_amethyst_bud',
    'amethyst_cluster': 'amethyst_cluster',
    'wildflowers': 'wildflowers',
    'leaf_litter': 'leaf_litter',
    'firefly_bush': 'firefly_bush',
    'resin_block': 'resin_block',
    'resin_clump': 'resin_clump',
    'resin_bricks': 'resin_bricks',
    'chiseled_resin_bricks': 'chiseled_resin_bricks',
    'pale_oak_leaves': 'pale_oak_leaves',
    'pale_oak_log': 'pale_oak_log',
    'pale_oak_planks': 'pale_oak_planks',
    'pale_oak_door': 'pale_oak_door_bottom',
    'pale_oak_trapdoor': 'pale_oak_trapdoor',
    'pale_oak_fence': 'pale_oak_fence',
    'pale_oak_fence_gate': 'pale_oak_fence_gate',
    'pale_oak_button': 'pale_oak_button',
    'pale_oak_pressure_plate': 'pale_oak_pressure_plate',
    'pale_oak_sign': 'pale_oak_sign',
    'pale_moss_block': 'pale_moss_block',
    'pale_moss_carpet': 'pale_moss_carpet',
    'pale_hanging_moss': 'pale_hanging_moss',
    'creaking_heart': 'creaking_heart',
    'open_eyeblossom': 'open_eyeblossom',
    'closed_eyeblossom': 'closed_eyeblossom',
    'copper_torch': 'copper_torch',
    'copper_lantern': 'copper_lantern',
    'exposed_copper_lantern': 'exposed_copper_lantern',
    'weathered_copper_lantern': 'weathered_copper_lantern',
    'oxidized_copper_lantern': 'oxidized_copper_lantern',
    'waxed_copper_lantern': 'waxed_copper_lantern',
    'waxed_exposed_copper_lantern': 'waxed_exposed_copper_lantern',
    'waxed_weathered_copper_lantern': 'waxed_weathered_copper_lantern',
    'waxed_oxidized_copper_lantern': 'waxed_oxidized_copper_lantern',
    'copper_chain': 'copper_chain',
    'exposed_copper_chain': 'exposed_copper_chain',
    'weathered_copper_chain': 'weathered_copper_chain',
    'oxidized_copper_chain': 'oxidized_copper_chain',
    'waxed_copper_chain': 'waxed_copper_chain',
    'waxed_exposed_copper_chain': 'waxed_exposed_copper_chain',
    'waxed_weathered_copper_chain': 'waxed_weathered_copper_chain',
    'waxed_oxidized_copper_chain': 'waxed_oxidized_copper_chain',
    'copper_bars': 'copper_bars',
    'exposed_copper_bars': 'exposed_copper_bars',
    'weathered_copper_bars': 'weathered_copper_bars',
    'oxidized_copper_bars': 'oxidized_copper_bars',
    'waxed_copper_bars': 'waxed_copper_bars',
    'waxed_exposed_copper_bars': 'waxed_exposed_copper_bars',
    'waxed_weathered_copper_bars': 'waxed_weathered_copper_bars',
    'waxed_oxidized_copper_bars': 'waxed_oxidized_copper_bars',
};

function mapBlockName(javaName) {
    if (!javaName) return 'missing_tile';

    let name = javaName.toLowerCase();

    if (name.includes(':')) {
        const parts = name.split(':');
        name = parts[1] || parts[0];
    }

    name = name.replace(/[^a-z0-9_]/g, '_');
    name = name.replace(/_+$/, '');

    const mapped = JAVA_TO_BEDROCK_BLOCK_MAP[name];
    if (mapped) {
        return mapped;
    }

    return name || 'missing_tile';
}

function getBlockParticleId(fullBlockName, isError = false) {
    if (!fullBlockName) {
        const suffix = isError ? 'error' : 'normal';
        return `litematica:block_missing_tile_${suffix}`;
    }

    let name = fullBlockName.toLowerCase();

    if (name.includes(':')) {
        const parts = name.split(':');
        name = parts[1] || parts[0];
    }

    name = name.replace(/[^a-z0-9_]/g, '_');
    name = name.replace(/_+$/, '');

    const mapped = JAVA_TO_BEDROCK_BLOCK_MAP[name];
    const textureName = mapped || name || 'missing_tile';

    const suffix = isError ? 'error' : 'normal';
    return `litematica:block_${textureName}_${suffix}`;
}

module.exports = {
    JAVA_TO_BEDROCK_BLOCK_MAP,
    mapBlockName,
    getBlockParticleId
};
